#!/bin/bash
sudo apt update
sudo apt install apache2  -y
sudo apt install unzip -y
wegt https://www.tooplate.com/zip-templates/2133_moso_interior.zip
unzip 2133_moso_interior.zip
sudo mv 2133_moso_interior/* /var/www/html/
sudo systemctl restart apache2.service
